### PR TITLE
Upgrade to stable components

### PR DESCRIPTION
**Pull request by denji**
* Grafana up to `v5.2.0`.
* InfluxData/InfluxDB up to `v1.5.4`.
* InfluxData/Telegraf up to `v1.7.0-1`.
* input-syslog `rewrite_tag_filter`: Migration deprecated `rewriterule*` to `rule`.
* input-syslog `rewrite_tag_filter`: Migrate all deprecated `type` to `@type`.
* input-snmp: Bugfix syntax error in the file parsing telegraf.conf, recent versions of Telegraf could have refused to read the snmp section.

### CODE REVIEW

**Comment by denji** [comment]
@3fr61n I've prepared the changes.

**Comment by 3fr61n** [comment]
@denji 
FYI..  A colleague @psagrera will be committing this week some pending changes we have (upgraded plugins and related dashboard),  so perhaps some of your changes need to be reviewed or are already covered for this changes.

Regards

**Comment by denji** [comment]
I agree.

I'm having problems with the migration to fluentd 1.x due to incompatibility of some APIs in ruby `Juniper/fluent-plugin-*` modules with `Fluent::TextParser`.

**Comment by henriklb** [comment]
influxdb web ui removed as of v1.3, I suggest adding Chronograf https://github.com/Juniper/open-nti/issues/225

**Pull request closed without merging**
