### PR TITLE
Docker Timezone

### PR DESCRIPTION
**Pull request by jorgebonilla**
Making the Docker Match the timezone of the host.

### CODE REVIEW

**Comment by dgarros** [comment]
Thanks @jorgebonilla for the contribution

We had something similar at the beginning of the project and I believe we removed it but I can't remember why :( 
The name of the file changed and I haven't been able to find the original version yet
@3fr61n do you remember why we took it off ?

**Comment by 3fr61n** [comment]
I think it was accidentaly removed  thanks @jorgebonilla

**Comment by dgarros** [comment]
@jorgebonilla, Please could you do the same change to the other startup scrip to make them consistent ?
```
docker.start.persistent.sh
```
Thanks

**Comment by dgarros** [comment]
Thanks a lot :)

**Pull request merged**
